# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('audience', models.BigIntegerField(verbose_name='audience')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Channel', verbose_name='channel')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start timestamp')),
                ('end', models.DateTimeField(verbose_name='end timestamp')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Channel', verbose_name='channel')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('count', models.IntegerField(verbose_name='count')),
                ('score', models.FloatField(verbose_name='score')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Segment', verbose_name='segment')),
            ],
        ),
    ]
